askme_Shibanov/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.new_questions, name='new_questions'),
    path('hot/', views.hot, name='hot_questions'),
    path('settings/', views.settings, name='settings'),
    path('tag/<str:question_tag>/', views.tag, name='tag'),
    path('question/<int:pk>/', views.question, name='question'),
    path('login/', views.login, name='login'),
    path('signup/', views.register, name='signup'),
    path('ask/', views.ask, name='ask'),
    path('logout/', views.logout, name='logout'),

    path('vote/', views.vote, name='vote'),
    path('correct/', views.correct, name='correct'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
import datetime

from django.db import models
import os
from django.conf import settings
from django.db.models import Count
from django.contrib.auth.models import User
from django.utils import timezone


def images_path():
    return os.path.join(settings.STATICFILES_DIRS, 'img')


class Profile(models.Model):
    class Meta:
        app_label = 'app'

    rating = models.IntegerField()
    avatar = models.ImageField(upload_to='avatar/%Y/%m/%d', default='ava.png')

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)

    AUTH_PROFILE_MODULE = 'app.Profile'


class QuestionManager(models.Manager):

    def new_questions(self):
        return Question.objects.order_by('-created_at')

    def best_questions(self):
        return Question.objects.all().annotate(num_likes=Count('questionlikes__id')).order_by('-num_likes')


class Tag(models.Model):
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Question(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    profile = models.ForeignKey(Profile, null=True, on_delete=models.SET_NULL)
    tag = models.ManyToManyField(Tag)

    objects = QuestionManager()


class Answer(models.Model):
    text = models.TextField()
    is_correct = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    profile = models.ForeignKey(Profile, null=True, on_delete=models.SET_NULL)
    question = models.ForeignKey(Question, null=True, on_delete=models.CASCADE)


class Questionlikes(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    question = models.ForeignKey(Question, on_delete=models.DO_NOTHING)


class Answerlikes(models.Model):  # unique_key
    created_at = models.DateTimeField(auto_now_add=True)

    profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    answer = models.ForeignKey(Answer, on_delete=models.DO_NOTHING)

templates/include/answer.html
{% load static %}

<div class="row question border border-1" id={{ answer.id }}>
    <div class="col-3">
        <div><img src={{ answer.profile.avatar.url }} class="question-img rounded img-fluid center-block d-block mx-auto"></div>
    </div>
    <div class="col-9">
        <div>
            {{ answer.text }}
        </div>
        <div class="row button-row justify-content-between">
            <div class="col-3">
                <input type="checkbox" class="btn-check" id="answer-{{ answer.id }}" autocomplete="off">
                <label class="btn btn-outline-success js-vote" data-aid="{{ answer.id }}" for="answer-{{ answer.id }}">Like <span
                        class="badge alert-success">{{answer.answerlikes_set.count}}</span></label>
            </div>
            <div class="col-3 correct-checkbox">
                <div class="form-check">
                    <input class="form-check-input js-correct" data-aid="{{ answer.id }}" data-qid={{one_question.id}} type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Correct!
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>

templates/include/best_answer.html
{% load static %}

<div class="row question border border-1 border-success first-answer">
    <div class="col-3">
        <div><img src="{{ best_answer.profile.avatar.url }}" class="question-img rounded img-fluid center-block d-block mx-auto"></div>
    </div>
    <div class="col-9">
        <div>
            {{best_answer.text}}
        </div>
        <div class="row button-row justify-content-between">
            <div class="col-3">
                <input type="checkbox" class="btn-check" id="btn-check-{{best_answer.id}}-outlined" autocomplete="off">
                <label class="btn btn-outline-success js-vote" data-aid="{{ best_answer.id }}" for="btn-check-{{best_answer.id}}-outlined">Like <span
                        class="badge alert-success" value="{{best_answer.answerlikes_set.count}}"></span></label>
            </div>
            <div class="col-3 correct-checkbox">
                <div class="form-check">
                    <input class="form-check-input js-correct" data-aid="{{ best_answer.id }}" data-qid={{one_question.id}} type="checkbox" value="" id="flexCheckChecked" checked>
                    <label class="form-check-label" for="flexCheckChecked">
                        Correct!
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>

templates/include/best_member.html
{% load static %}

<div class="row">
	<div class="col-2">
		<a href="#"> <img src="{{ member.avatar.url }}" class="member-img-container rounded img-fluid"> </a>
	</div>
	<div class="col-9">
	<a href="#" class="text-decoration-none">{{ member.user.username }}</a>
	</div>
	<div class="col-1">
	<span class="badge alert-info">{{ member.rating }}</span>
	</div>
</div>

templates/include/dark_navbar.html
{% load static %}

<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url "new_questions" %}">AskShibanov</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
        </ul>
        <div class="d-flex">
          <a role="button" href="{% url "ask" %}" class="btn btn-outline-success me-5" type="submit">
            ASK!
          </a>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "settings" %}">
                <img src="{{ request.user.profile.avatar.url }}" class="rounded img-fluid" width="20" alt="avatar">
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "logout" %}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "login" %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url "signup" %}">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

templates/include/one_question.html
{% load static %}
<div class="row question">
  <div class="col-3">
      <span class="img-container"><img src="{{ one_question.profile.avatar.url }}" class="question-img rounded img-fluid center-block d-block mx-auto"></span>
  </div>
  <div class="col-9">
      <div><a href="{% url "question" pk=one_question.id %}" class="text-decoration-none"><h2>{{ one_question.title }}</h2></a></div>
      <div>
          {{ one_question.text }}
      </div>
      <div class="row button-row">
          <div class="col-4">
              <a role="button" href="{% url "question" pk=one_question.id %}" class="btn btn-outline-primary">Answers <span class="badge alert-primary">{{one_question.answer_set.count}}</span></a>
          </div>
          <div class="col-3">
              <input type="checkbox" class="btn-check" id="question-{{ one_question.id }}" autocomplete="off">
              <label class="btn btn-outline-success js-vote" data-qid="{{ one_question.id }}" for="question-{{ one_question.id }}">Like <span class="badge alert-success">{{one_question.questionlikes_set.count}}</span></label>
          </div>
          <div class="col-5">
              Tags:
              {% for tag in one_question.tag.all %}
              <a role="button" href="{% url "tag" question_tag=tag.name %}" class="btn btn-light"> {{ tag.name }}</a>
              {% endfor %}
          </div>
      </div>
  </div>
</div>

templates/include/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pag_item.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ pag_item.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
        <li class="page-item"><a class="page-link" href="?page=2">2</a></li>
        <li class="page-item"><a class="page-link" href="?page=3">3</a></li>
        {% if pag_item.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ pag_item.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>

templates/include/questionpage_question.html
{% load static %}

<div class="row question shadow-lg">
    <div class="col-4">
        <div><img src="{{ one_question.profile.avatar.url }}" class="question-page-question-img rounded img-fluid center-block d-block mx-auto">
        </div>
    </div>
    <div class="col-8">
        <div><h1 class="text-secondary">{{ one_question.title }}</h1></div>
        <div>
            {{ one_question.text }}
        </div>
        <div class="row button-row">
            <div class="col-6">
                <input type="checkbox" class="btn-check" id="btn-check-{{one_question.id}}-outlined" autocomplete="off">
                <label class="btn btn-outline-success js-vote" data-qid="{{ one_question.id }}" for="btn-check-{{one_question.id}}-outlined">Like <span
                        class="badge alert-success">{{one_question.questionlikes_set.count}}</span></label>
            </div>
            <div class="col-6">
                Tags:
                {% for tag in one_question.tag.all %}
              <a role="button" href="{% url "tag" question_tag=tag.name %}" class="btn btn-light"> {{ tag.name }}</a>
              {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/include/tags_members.html
{% load static %}
<h4>Popular Tags</h4>
<div class="tags-collection right-side-block">
    {% for tag in popular_tags %}
        <a href="{% url "tag" question_tag=tag.name %}"><span class="badge badge-pill alert-success">{{tag.name}}</span></a>
    {% endfor %}
</div>

<h4>Best Members</h4>
<div class="best-members right-side-block">
    {% for member in best_members %}
        {% include "include/best_member.html" %}
    {% endfor %}
</div>